// Real T-VER project data based on TGO Registry (2024-2025)
// Source: ghgreduction.tgo.or.th / tver.tgo.or.th

export const REAL_TVER_PROJECTS = [
  {
    id: 1,
    tgo_registration_number: "T-VER-F-0089",
    name: "BCPG Mangrove Rehabilitation Project for a Sustainable World",
    name_th: "โครงการฟื้นฟูป่าชายเลนของ BCPG เพื่อโลกที่ยั่งยืน",
    forest_type: "mangrove",
    status: "monitoring",
    methodology: "T-VER-P-METH-13-02",
    province: "ระยอง",
    district: "บ้านฉาง",
    area_rai: 1250,
    project_start_date: "2019-01-01",
    crediting_period_years: 15,
    registration_date: "2019-06-15",
    expected_reduction_tco2_year: 791,
    total_issued_tco2: 3164,
    next_verification_due: daysFromNow(280),
    verification_cycle_years: 3,
    owner_org: "บริษัท บีซีพีจี จำกัด (มหาชน)",
    co_benefits: { biodiversity: true, water: true, community: true, sdg13: true, sdg14: true, sdg15: true },
    last_monitoring_date: "2022-12-31",
  },
  {
    id: 2,
    tgo_registration_number: "T-VER-F-0142",
    name: "Community Forestry Baan Pa Sang Doi Kaew, Chiang Rai",
    name_th: "โครงการป่าชุมชนบ้านป่าซางดอยแก้ว อ.เวียงเชียงรุ้ง จ.เชียงราย",
    forest_type: "community",
    status: "monitoring",
    methodology: "T-VER-S-METH-13-01",
    province: "เชียงราย",
    district: "เวียงเชียงรุ้ง",
    area_rai: 4250,
    project_start_date: "2018-01-01",
    crediting_period_years: 10,
    registration_date: "2018-09-20",
    expected_reduction_tco2_year: 2135,
    total_issued_tco2: 14945,
    next_verification_due: daysFromNow(45),
    verification_cycle_years: 2,
    owner_org: "กลุ่มป่าชุมชนบ้านป่าซางดอยแก้ว",
    co_benefits: { biodiversity: true, water: true, community: true, sdg13: true, sdg15: true },
    last_monitoring_date: "2024-01-15",
  },
  {
    id: 3,
    tgo_registration_number: "T-VER-F-0215",
    name: "Community Forestry Baan Ton Peung, Mae Phong, Doi Saket, Chiang Mai",
    name_th: "โครงการป่าชุมชนบ้านต้นผึ้ง แม่โป่ง ดอยสะเก็ด จ.เชียงใหม่",
    forest_type: "community",
    status: "monitoring",
    methodology: "T-VER-S-METH-13-01",
    province: "เชียงใหม่",
    district: "ดอยสะเก็ด",
    area_rai: 862,
    project_start_date: "2020-01-01",
    crediting_period_years: 10,
    registration_date: "2020-05-10",
    expected_reduction_tco2_year: 315,
    total_issued_tco2: 1055,
    next_verification_due: daysFromNow(-15), // overdue
    verification_cycle_years: 2,
    owner_org: "ป่าชุมชนบ้านต้นผึ้ง",
    co_benefits: { biodiversity: true, water: true, community: true },
    last_monitoring_date: "2024-04-01",
  },
  {
    id: 4,
    tgo_registration_number: "T-VER-F-0272",
    name: "Community Forestry Baan Tau Pae, Mae Hong Son",
    name_th: "โครงการป่าชุมชนบ้านต่อแพ อ.ขุนยวม จ.แม่ฮ่องสอน",
    forest_type: "community",
    status: "issued",
    methodology: "T-VER-S-METH-13-01",
    province: "แม่ฮ่องสอน",
    district: "ขุนยวม",
    area_rai: 15400,
    project_start_date: "2017-01-01",
    crediting_period_years: 10,
    registration_date: "2017-08-16",
    expected_reduction_tco2_year: 8500,
    total_issued_tco2: 10182,
    next_verification_due: daysFromNow(320),
    verification_cycle_years: 2,
    owner_org: "ป่าชุมชนบ้านต่อแพ",
    co_benefits: { biodiversity: true, water: true, community: true, sdg13: true, sdg15: true },
    last_monitoring_date: "2024-08-16",
  },
  {
    id: 5,
    tgo_registration_number: "T-VER-F-0040",
    name: "Forest Industry Organization — Phrae Reforestation Project",
    name_th: "โครงการปลูกป่าขององค์การอุตสาหกรรมป่าไม้ จ.แพร่ (TVER-40)",
    forest_type: "restoration",
    status: "issued",
    methodology: "T-VER-S-METH-13-01",
    province: "แพร่",
    district: "ร้องกวาง",
    area_rai: 28600,
    project_start_date: "2015-01-01",
    crediting_period_years: 10,
    registration_date: "2016-03-01",
    expected_reduction_tco2_year: 43628,
    total_issued_tco2: 87256,
    next_verification_due: daysFromNow(180),
    verification_cycle_years: 2,
    owner_org: "องค์การอุตสาหกรรมป่าไม้ (FIO)",
    co_benefits: { biodiversity: true, water: true, community: true, sdg13: true, sdg15: true, sdg8: true },
    last_monitoring_date: "2023-12-31",
    tgo_source_url: "https://www.carbonmark.com/post/thailand-s-t-ver-carbon-credits-now-available-via-carbonmark-api",
  },
  {
    id: 6,
    tgo_registration_number: "T-VER-A-0596",
    name: "Carbon Credit Management of the Rubber Authority of Thailand 2025",
    name_th: "โครงการบริหารจัดการคาร์บอนเครดิตของการยางแห่งประเทศไทย ปี 2568 เขตภาคกลางและภาคตะวันออก",
    forest_type: "rubber",
    status: "registered",
    methodology: "T-VER-S-METH-13-06",
    province: "ชลบุรี",
    district: "หลายจังหวัด (Bundling)",
    area_rai: 125000,
    project_start_date: "2025-07-05",
    crediting_period_years: 7,
    registration_date: "2025-11-25",
    expected_reduction_tco2_year: 185000,
    total_issued_tco2: 0,
    next_verification_due: daysFromNow(540),
    verification_cycle_years: 2,
    owner_org: "การยางแห่งประเทศไทย (RAOT)",
    co_benefits: { community: true, sdg8: true, sdg13: true },
    last_monitoring_date: null,
  },
  {
    id: 7,
    tgo_registration_number: "T-VER-F-0523",
    name: "Mangrove Planting Project 2023 by Thai Special Gas Co., Ltd.",
    name_th: "โครงการปลูกป่าชายเลน เพื่อประโยชน์จากคาร์บอนเครดิต ประจำปี 2566 โดย บริษัท ไทยสเปเชี่ยลแก๊ส จำกัด",
    forest_type: "mangrove",
    status: "registered",
    methodology: "T-VER-S-METH-13-01",
    province: "ชุมพร",
    district: "ทุ่งตะโก",
    area_rai: 180,
    project_start_date: "2025-01-23",
    crediting_period_years: 10,
    registration_date: "2025-07-22",
    expected_reduction_tco2_year: 289,
    total_issued_tco2: 0,
    next_verification_due: daysFromNow(600),
    verification_cycle_years: 2,
    owner_org: "บริษัท ไทยสเปเชี่ยลแก๊ส จำกัด",
    co_benefits: { biodiversity: true, water: true, sdg13: true, sdg14: true },
    last_monitoring_date: null,
  },
  {
    id: 8,
    tgo_registration_number: "T-VER-F-0372",
    name: "PTT Forestation in Natural Gas Pipeline Areas",
    name_th: "โครงการปลูกป่าในพื้นที่ดำเนินการระบบท่อส่งก๊าซธรรมชาติ บริษัท ปตท. จำกัด (มหาชน)",
    forest_type: "restoration",
    status: "monitoring",
    methodology: "T-VER-S-METH-13-01",
    province: "ระยอง",
    district: "หลายจังหวัด (Bundling)",
    area_rai: 3200,
    project_start_date: "2023-11-02",
    crediting_period_years: 10,
    registration_date: "2024-03-11",
    expected_reduction_tco2_year: 108,
    total_issued_tco2: 0,
    next_verification_due: daysFromNow(90),
    verification_cycle_years: 2,
    owner_org: "บริษัท ปตท. จำกัด (มหาชน) + Carbon Scout",
    co_benefits: { community: true, sdg13: true, sdg15: true },
    last_monitoring_date: null,
  },
  {
    id: 9,
    tgo_registration_number: "T-VER-F-0412",
    name: "Somrom Agroforestry — Koh Yor Community, Songkhla",
    name_th: "โครงการสวนสมรมชุมชนเกาะยอ จ.สงขลา (Pilot SomromScan v2)",
    forest_type: "somrom",
    status: "validating",
    methodology: "T-VER-S-METH-13-01",
    province: "สงขลา",
    district: "เกาะยอ",
    area_rai: 850,
    project_start_date: "2024-01-01",
    crediting_period_years: 10,
    registration_date: null,
    expected_reduction_tco2_year: 620,
    total_issued_tco2: 0,
    next_verification_due: daysFromNow(200),
    verification_cycle_years: 2,
    owner_org: "กลุ่มเกษตรกรสวนสมรมเกาะยอ",
    co_benefits: { biodiversity: true, water: true, community: true, sdg13: true, sdg15: true, sdg2: true },
    last_monitoring_date: null,
    notes: "โครงการ pilot ของ SomromScan v2 MRV Platform — ใช้ sensor IoT + ARCore วัด AGB",
  },
  {
    id: 10,
    tgo_registration_number: "T-VER-F-0451",
    name: "Nakhon Si Thammarat Rubber-Agroforestry Carbon Project",
    name_th: "โครงการคาร์บอนเครดิตสวนยางพาราวนเกษตร จ.นครศรีธรรมราช",
    forest_type: "rubber",
    status: "registered",
    methodology: "T-VER-S-METH-13-01",
    province: "นครศรีธรรมราช",
    district: "ทุ่งสง",
    area_rai: 3800,
    project_start_date: "2023-06-01",
    crediting_period_years: 10,
    registration_date: "2024-01-15",
    expected_reduction_tco2_year: 1840,
    total_issued_tco2: 0,
    next_verification_due: daysFromNow(350),
    verification_cycle_years: 2,
    owner_org: "สหกรณ์ชาวสวนยางนครศรีธรรมราช",
    co_benefits: { community: true, sdg8: true, sdg13: true },
    last_monitoring_date: null,
  },
  {
    id: 11,
    tgo_registration_number: "T-VER-F-0481",
    name: "Phang Nga Bay Mangrove Restoration",
    name_th: "โครงการฟื้นฟูป่าชายเลนอ่าวพังงา",
    forest_type: "mangrove",
    status: "monitoring",
    methodology: "T-VER-P-METH-13-02",
    province: "พังงา",
    district: "เกาะยาว",
    area_rai: 960,
    project_start_date: "2021-06-01",
    crediting_period_years: 15,
    registration_date: "2021-12-01",
    expected_reduction_tco2_year: 580,
    total_issued_tco2: 2100,
    next_verification_due: daysFromNow(-8), // overdue
    verification_cycle_years: 3,
    owner_org: "กรมทรัพยากรทางทะเลและชายฝั่ง + อบต.เกาะยาว",
    co_benefits: { biodiversity: true, water: true, community: true, sdg13: true, sdg14: true },
    last_monitoring_date: "2024-06-01",
  },
  {
    id: 12,
    tgo_registration_number: "T-VER-F-0501",
    name: "Surat Thani Community Forest Carbon Sequestration",
    name_th: "โครงการกักเก็บคาร์บอนป่าชุมชน จ.สุราษฎร์ธานี",
    forest_type: "community",
    status: "draft",
    methodology: "T-VER-S-METH-13-01",
    province: "สุราษฎร์ธานี",
    district: "บ้านนาสาร",
    area_rai: 1440,
    project_start_date: "2025-01-01",
    crediting_period_years: 10,
    registration_date: null,
    expected_reduction_tco2_year: 420,
    total_issued_tco2: 0,
    next_verification_due: daysFromNow(730),
    verification_cycle_years: 2,
    owner_org: "เทศบาลตำบลนาสาร",
    co_benefits: { biodiversity: true, community: true, sdg13: true },
    last_monitoring_date: null,
  },
]

// Carbon credit transactions (realistic T-VER market data)
export const CARBON_TRANSACTIONS = [
  { id: 1, project_id: 5, buyer: "บริษัท ปตท. จำกัด (มหาชน)", credits_tco2: 5000, price_thb: 1850, date: "2024-11-15", type: "retirement", vintage: "2023" },
  { id: 2, project_id: 4, buyer: "บริษัท ไทยเบฟเวอเรจ จำกัด (มหาชน)", credits_tco2: 2000, price_thb: 1720, date: "2024-10-20", type: "retirement", vintage: "2024" },
  { id: 3, project_id: 2, buyer: "การบินไทย (CORSIA Phase 1)", credits_tco2: 3500, price_thb: 2076, date: "2024-09-01", type: "retirement", vintage: "2024" },
  { id: 4, project_id: 1, buyer: "บริษัท เอสซีจี จำกัด (มหาชน)", credits_tco2: 1500, price_thb: 1900, date: "2024-08-15", type: "retirement", vintage: "2023" },
  { id: 5, project_id: 5, buyer: "บริษัท กสิกรไทย จำกัด (มหาชน)", credits_tco2: 8000, price_thb: 1750, date: "2024-07-30", type: "transfer", vintage: "2022" },
  { id: 6, project_id: 3, buyer: "บริษัท เซ็นทรัล รีเทล จำกัด (มหาชน)", credits_tco2: 800, price_thb: 1680, date: "2024-06-15", type: "retirement", vintage: "2024" },
  { id: 7, project_id: 4, buyer: "Carbonmark (International)", credits_tco2: 1200, price_thb: 2200, date: "2025-01-10", type: "transfer", vintage: "2024" },
  { id: 8, project_id: 2, buyer: "TrueMoney Wallet Users", credits_tco2: 450, price_thb: 39, date: "2025-03-01", type: "retirement", vintage: "2024" },
]

// Market price history (real approximate data)
export const CARBON_PRICE_HISTORY = [
  { month: "2023-07", price_thb: 125, volume: 45200 },
  { month: "2023-09", price_thb: 142, volume: 62800 },
  { month: "2023-11", price_thb: 168, volume: 89400 },
  { month: "2024-01", price_thb: 155, volume: 74300 },
  { month: "2024-03", price_thb: 174, volume: 95600 },
  { month: "2024-05", price_thb: 189, volume: 112400 },
  { month: "2024-07", price_thb: 1720, volume: 38900 },  // Premium T-VER approved
  { month: "2024-09", price_thb: 1850, volume: 52300 },
  { month: "2024-11", price_thb: 1950, volume: 68100 },
  { month: "2025-01", price_thb: 1900, volume: 71200 },
  { month: "2025-03", price_thb: 2076, volume: 84500 },
  { month: "2025-05", price_thb: 2100, volume: 91800 },
]

// Helper
function daysFromNow(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString()
}
